### ISSUE TITLE
Change folder structure to a more readable structure

### ISSUE THREAD

**Issue by DevManu-de** [myzhang1029/psh#22]
Hello Maiyun,

I'm opening this issue because I have trouble getting fimiliar to the files even with the documentation. (and I can imagine others have similar troubles and therefore not wanting to contribute) I really want to contribute to the project and therefore I suggest to change the folder structure to a more readable and understandable structure like this below and in the same run I want rename or move files to prevent confusion. (all the test files in the libpsh folder)

```
psh
  |-- src
  |     |-- main.c
  |-- lib
  |      |-- utilities
  |      |      |--util.c
  |      |      |-- "and other .c files that include the definitios of the functions in the corresponding header files like xmalloc.c"
  |      |-- history
  |             |-- history.c
  |-- include
  |      |-- utilities
  |      |      |--util.h
  |      |      |-- "and other header files that include utlities like xmalloc.h"
  |      |-- history
  |             |-- history.h
  |-- bin
        |-- "All output files go here"

```
I also have found a tool that could we make use of (https://github.com/danielpinto8zz6/c-cpp-project-generator) (also in the VS Code extension repository https://marketplace.visualstudio.com/items?itemName=danielpinto8zz6.c-cpp-project-generator) I have used this in the past and it worked really well and its cross platform. In addition to that it doesnt use cmake only make. It would be enough to copy the template Makefile from the repository and create the rest by hand.

I can understand if you are sceptical (I would be) about those changes that are comming from a stranger from across the world that has only contributed a small file. Im aware that those changes take some time to complete.

In case you want to give my idea a try, I have created a list below that consists of all necessary changes that have be done in order to get all files to the new structure (of course I'll help with this).

- [x] create a new branch
- [x] create new folder structure
- [x] make seperate folders for the test files
- [x] categorizing the header files
- [x] seperate .h files from .c
- [x] move / rename files
- [x] adjust the makefile
- [x] update the doxygen file
- [x] run checks
- [x] adjust readme file

Before I make changes to my local files I want to get your opinion on this topic.

I hope you consider my idea as usefull and I hope you'll give it a try.
Looking forward to your response. 

Sincerely,
Manuel

P.S. Can you give me a more detailed explanation of what you are doing exactly and what you have achieved so far especially in #2 #8 #18

**Comment by myzhang1029** [comment]
Hi Manuel,

I love this new structure. I agree especially with `make separate folders for the test files` and `seperate .h files from .c`.

I agree that my projects all have poor documentation. I have been working alone on my projects, and have never imagined some nice people like you would join. But I am willing to create one together. And I am not a native English speaker, so I might sound unnatural or even a little unfriendly, but I didn't mean that, I am pretty friendly. I am also a full-time student, so sometimes I might reply late or have limited time.

However, I would like to discuss a few things with you before adopting the new structure.

First, I want to review the aims of this project together.

> Psh aims to be able to compile on as many C99 systems as possible, providing a highly emulated POSIX environment. To reach this goal, psh juices out those platform-dependent parts, for example, subprocess management and user data extraction, into backends.

As an approach to the aims, this project actually consists of two parts, `psh` and `libpsh`. `psh` is the _shell_  itself, while `libpsh` contains the utilities that
- are made alongside the development that might be useful to other projects.
- are platform-independent, i.e. not dependent on POSIX APIs or WinAPIs, uses only standard C (ANSI, C99 or C11) features.
- are not a shell functionality, i.e. not `variables`, not `command execution`
So I would like to stick to this two-part division currently, but you may convince me.

In case you are wondering, although `psh/backend` contains only one file now, in the future I plan to write more, maybe with you. The backends are the platform-dependent parts, like all POSIX APIs, GNU extensions (I prefer not to use them). At least one for Windows (#12) and a “generic” one, which is for unimplemented OSes (#14).

Second, for your `history`, this project has been using [GNU history](https://tiswww.case.edu/php/chet/readline/history.html), although the current code is `psh` is not working very well. `GNU history` already provides history saving/reloading, so I wonder if we have to write another history manager. However, we can certainly create a new one, maybe using some databases to increase performance? I haven’t made my mind yet.

Third, the `psh/builtins` folder is another one I would suggest to keep. I believe this can keep things more organized, as the files in `builtins/` are more like mini-programs on their own.

Therefore, I suggest changing the directory layout to something like (edited from yours)
```
top level
  |-- src
  |     |-- builtins
  |     |     |-- echo.c
  |     |     |-- and other shell builtins
  |     |-- builtins.c // This is different from builtins/, please ask if in doubt.
  |     |-- main.c
  |     |-- command.c
  |     |-- variable.c
  |     |-- and other .c files relating to shell functions
  |-- lib
  |     |-- util.c
  |     |-- xmalloc.c
  |     |-- and other .c files in libpsh/ except tests and maybe history.c
  |-- include
  |     |-- libpsh
  |     |     |-- util.h
  |     |     |-- and other .h files in libpsh/
  |     |-- command.h
  |     |-- and other .h files in psh/
  |-- test
  |     |-- test code
  |-- bin
  |     |-- all output files go here
```

About the build system, I am still skeptical about it. I would rather not use a build system that is bound to an editor. Sometimes I even have to code on places without a GUI. Another point is (not sure if you have noticed,) `select_backend.c` is generated based on the operating system. Using CMake here is currently more or less a hack, maybe a better method can be used.

Last, here are the clarifications about the issues.

-       #2
You can refer back to [README.md](https://github.com/myzhang1029/psh/blob/dev-redirect-handle/README.md), this project was a fork of vvy/wshell, but I would like to completely remove and rewrite the original code, either from `git blame` or if they are actually original code but not shown in `git blame` for some reasons.

-       #8
It is just variables in a shell. I plan to include functions as variables. It is what `bash` seems to be doing from the behavior, but I’m not sure about its actual implementation. But one thing I would like to be different from `bash` is to allow local function. I haven’t yet decided whether to include aliases as variables.

-       #18
It is just shell options, i.e. the `--interactive` option you pass to `bash`, or things you set with `shopt`.

Good luck and thank you again!

Regards,
Maiyun Zhang

**Comment by DevManu-de** [comment]
Hey Maiyun,

Im happy that you are open for such a big change. I know that my structure plan is not complete because I just wanted to give you a small impression of what my idea is and how it could look like.
I appreciate your time that you put in your comment to explain me what the folders mean and what they contain.

Im not a native English speaker and Im also working full time. So my time is also pretty limited.

I agree in a discussion before adopting the changes to work out the smaller details of the project but also Im not sure how we could achieve this due to the 8 hour time difference we both have. Im unsure how to make a discussion that does not require one of us to wait 12 hours for a response. (I mean it would work but would take a long time to figure out all details).

When it comes to the history file that I made. Im open for suggestions for another history system, maybe we could use the GNU one but we may have to rewrite some stuff to make it compatible with psh.

Now about your skeptisism about the build system, I think you got me wrong the first time, the tool (https://github.com/danielpinto8zz6/c-cpp-project-generator) can be used with ease from the terminal, it is NOT bound to a GUI it can simply be use with the command `make run`, when in the directory containing the Makefile. For our project we just need to copy the Makefile and create all required directories to make it work. I wrote my on .sh file to simplify this process but my .sh file only creates a Linux / MacOS compatible Makefile and would therefore not work on Windows without some changes. (Windows version is required to achieve our aims to make it cross platform).

There is an image of what it looks like using the tool. (tree command not required only for understandability)

main.c
```
#include <stdio.h>
#include "../include/test.h"

int main(){

    printf("Hello\n");
    test();

}
```
test.h
```
void test();
```

test.c
```
#include <stdio.h>

void test(){

    puts("TEST");

}
```
NOTE: This is not my usual coding style, this is only to demonstrate the tool! The bin/main is a leftover from my test.

![20201030 185232](https://user-images.githubusercontent.com/68355512/97740097-0643c300-1ae1-11eb-988b-20e1e1d2d3d2.jpg)


The command `make run` compiles all files and executes them.

I mentioned the VS Code extension because I saw the .vscode folder in the psh repository and assumed you prefer VS Code. Personally speaking I prefer Emacs / vim depending on my planned changes. Means, when I write a completely new function I would use Emacs (Doom Emacs) due to its code completion and other useful tools. (I know that vim has this extensions too but I prefer keeping vim (neovim) as light as possible to improve its performance). I use vim when I want to make a minor change and dont need all the fancy extensions.

Good luck.


Sincerely,
Manuel

**Comment by DevManu-de** [comment]
Hey Maiyun,

I have been experimenting with libraries and linking in c for the past days and thought maybe it's a good idea to make libraries from the .c files in the lib folder and link them, when we change to a new folder structure.

Pros:
- small performance provement when compiling
- no need to include the .h file
- avoid confusion

Cons:
- extra step required when modifying the corresponding .c file
- modify the makefile when new libraries come

Creating a library is fairly easy, just compile the file.c file (gcc -c file.c) and then use `ar rcs lib.a  file.o` to create a library.
To link a library just add -L. -llib. more information here https://randu.org/tutorials/c/libraries.php
The -L flag is already in the makefile.

I would like to hear your optinion on this topic and my previous comment because you haven't respond to it yet (I mean it in a friendly way. I know you have much work. No need to feel in a hurry).

Good luck.

Sincerely,
Manuel

**Comment by myzhang1029** [comment]
Hey,

Yes, you are right. It is a good idea to create a library. But I’m not sure if you have noticed, the files under `libpsh/` are already compiled as a static library. The only difference is that CMake is taking care of generating that command (`ar rcs …`) you provided (the corresponding directive is [here]( https://github.com/myzhang1029/psh/blob/4535b993251dcd0f50bee6d6da1ddaae8f150c61/libpsh/CMakeLists.txt#L3)).

I wasn’t responding because I was waiting to see if you would like to actually change the structure and get your hand on committing and sending a PR.

As for the build system, the one you proposed and CMake can co-exist.  If you are not familiar with CMake, don’t worry, and I’ll take care of the rest. The current solution is certainly not the best, so don’t hesitate to propose or ask if in doubt.

Best,
Maiyun Zhang

**Comment by DevManu-de** [comment]
Hey,

Over the past hours I made a working version of psh in the new folder structure. Currently I put everything in without checking if the header file is required or anything. I temporarily removed the your version of posix.c (posix2.c) from the backend because it caused some conflict with the existing posix.c. The compilder is mainly complaining about unused parameters and unused functions. (To compile it your self, First clean everything with ```make clean``` and then run ```make``` or ```make run``` to just compile or compile and run) There is still a lot of work to do.

I would like to hear your feedback. (Check it out here: https://github.com/DevManu-de/psh)

Regards,
Manuel

**Comment by DevManu-de** [comment]
Hello,

to finalize this change, you only need to remove the unnecessary Makefile that I created and change in the Readme.md
`psh/psh` -> `src/psh`.
After this is done we can go and work on other parts of psh.

Best,
Manuel
