### ISSUE TITLE
Possible bug with &

### ISSUE THREAD

**Issue by DevManu-de** [myzhang1029/psh#33]
Im trying to implement the `wait` builtin and I noticed a potential bug.
If I call my terminal emulator `st` from psh with `st &` and then kill the newly created `st` then `st` still exists in `htop` as a zombie process.
Im sure this is not intended.

**Comment by myzhang1029** [comment]
No, it is surely not intended. However, all job-related things are being rewritten, so maybe you would like to implement some other things.
