### ISSUE TITLE
Question about the current state of the project

### ISSUE THREAD

**Issue by DevManu-de** [myzhang1029/psh#37]
Hello @myzhang1029,

I havent heard nor seen you on this project for about a month can you please tell me if the project is just paused or if something else occured.

I would really appreciate an answer even if it says the project is paused.
I hope we can continue developing psh soon.

Good luck.

Sincerely,
Manuel

**Comment by myzhang1029** [comment]
I am really sorry, should have replied to your messages. I am just really busy these days with my school work, so maybe you can just work on whatever you want and I will come back in just a few days.
